name: Build and Release EXE

on:
  push:
    branches:
      - main

permissions:
  contents: write  # <<< PERMETTE LA CREAZIONE DELLA RELEASE

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if exist requirements.txt (pip install -r requirements.txt)

      - name: Build EXE
        run: |
          pyinstaller --onefile main.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_executable
          path: dist/main.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my_executable
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          files: ./dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
